apiVersion: v1
kind: Service
metadata:
  name: nextapp-cicd-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: nextapp-cicd-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
